name: Publish to NPM
on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v1

      - name: Setup Node.js
        uses: actions/setup-node@v1
        with:
          node-version: "18" # Use the desired Node.js version
          registry-url: "https://registry.npmjs.org"

      - name: Install dependencies and build 🔧
        run: 
          npm install -g @angular/cli@14.2.0
          npm ci
          ng build --configuration production

      - name: Publish package on NPM 📦
        run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{secrets.NPM_TOKEN}}
